version: "3.8"

services: 
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./server:/server
    working_dir: /server
    restart: unless-stopped
  

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports: 
      - "3000:3000"
    volumes:
      - ./client:/app
    working_dir: /app
    restart: unless-stopped
